### ISSUE TITLE
Is `Syntax Highlighting` works?

### ISSUE THREAD

**Issue by rediffusion** [yedhrab/YAutoHotkey-VSCode#3]
Selamla!

I installed this extension. `Syntax Highlighting` seems not working. I have `eppz!` theme and see his highlighting, not yours. 
 Find this file `syntax.xml` where's references to this file? Have the same file for "Notepad++" it's works and highlights fine.

Allah beterinden korusun!

**Comment by yemreak** [comment]
🙋‍♂️ Selam

This extension have tested just on [🖤🤍DarkCode](https://marketplace.visualstudio.com/items?itemName=yedhrab.darkcode-theme-adopted-python-and-markdown) theme and works for only this theme yet.

![image](https://user-images.githubusercontent.com/49655146/73103228-af331100-3f04-11ea-8c01-23befafa97bd.png)

**Comment by rediffusion** [comment]
@yedhrab 

`.\YAutoHotkey-VSCode\syntax.xml`

Find this file `syntax.xml` where's references to this file? Have the same file for "Notepad++" it works and highlights fine. How you make it work? If I put something like this, will this work?

> JavaScript_syntax.xml
> C#_syntax.xml
> C_syntax.xml
> C++_syntax.xml

**Comment by yemreak** [comment]
- 🕯️ There is no references. VSCode use  `syntaxes/ahk.tmLanguage` file instead of `syntax.xml`.
- 💁‍♂️ You don't need to anything to make it works. (It's already works)
- 💡 The extension just present keywords to themes and themes colorize.
- ✖️ Without this extension, your theme can't colorize them
- ✨ To make additional syntax works, you need to use [🖤🤍DarkCode](https://marketplace.visualstudio.com/items?itemName=yedhrab.darkcode-theme-adopted-python-and-markdown) theme

> 💦 Now, I deleted `syntax.xml` file.
